---
 apiVersion: v1
 kind: Namespace
 metadata:
   name: clouda-commerce
---
 apiVersion: networking.k8s.io/v1
 kind: Ingress
 metadata:
   namespace: clouda-commerce
   name: ingress-clouda-commerce-green
   annotations:
     alb.ingress.kubernetes.io/scheme: internet-facing
     alb.ingress.kubernetes.io/target-type: ip
     alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":8081}]'
     alb.ingress.kubernetes.io/load-balancer-name: clouda-commerce-green
     alb.ingress.kubernetes.io/group.name: clouda-commerce.green


 spec:
   ingressClassName: alb
   rules:
     - host: www.example.com
       http:
         paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: service-clouda-commerce-api
               port:
                 number: 8081
