---
apiVersion: v1
kind: Namespace
metadata:
  name: blue-green
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: blue-green
  name: blue-green
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: blue-green-app
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blue-green-app
    spec:
      containers:
      - image: yasirub/blue-green:latest
        imagePullPolicy: Always
        name: blue-green-app
        env:
        - name: cluster_color
          value: "Blue"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: blue-green
  name: blue-green-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: blue-green-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: blue-green
  name: blue-green-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: blue-alb-group
    alb.ingress.kubernetes.io/load-balancer-name: blue-alb
    #alb.ingress.kubernetes.io/subnets: subnet-011bf7846593749bf, subnet-06b3eb497e3f1a849

spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: blue-green-service
              port:
                number: 80
