---
 apiVersion: v1
 kind: Namespace
 metadata:
   name: clouda-commerce
---
 apiVersion: networking.k8s.io/v1
 kind: Ingress
 metadata:
   namespace: clouda-commerce
   name: ingress-clouda-commerce
   annotations:
     alb.ingress.kubernetes.io/scheme: internet-facing
     alb.ingress.kubernetes.io/target-type: ip
     alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":8080}]'
     alb.ingress.kubernetes.io/load-balancer-name: clouda-commerce-blue
     alb.ingress.kubernetes.io/group.name: clouda-commerce.blue

 spec:
   ingressClassName: alb
   rules:
     - host: www.abc.com
       http:
         paths:
         - path: /db
           pathType: Prefix
           backend:
             service:
               name: db
               port:
                 number: 5471